#!/usr/bin/env ruby

$LOAD_PATH.unshift File.dirname($0)

require 'yaml'
require 'hashes2ostruct'

def changelog2markdown(changelog, io)
  changelog.each do |release|
    title = "Version #{release.version} -- #{release.date}"
    io.puts title
    io.puts "-" * title.size
    io.puts
    release.changes.each do |change|
      io.puts "* " + change
    end
    io.puts
  end
end

changelog = hashes2ostruct(YAML.load_file(ARGV[0]))
changelog2markdown(changelog, $stdout)
