#!/usr/bin/env ruby

$LOAD_PATH.unshift File.join(File.dirname($0), "lib")

require 'yaml'
require 'time'
require 'changelog'

def changelog2markdown(changelog, io)
  separator = ""
  changelog.each do |release|
    release_date = release.date.strftime("%d %b %Y")
    title = "Version #{release.version} -- #{release_date}"
    io.print separator
    io.puts title
    io.puts "-" * title.size
    io.puts
    release.changes.each do |change|
      io.puts "* " + change
    end
    separator = "\n\n"
  end
end

changelog = read_changelog(ARGV[0])
changelog2markdown(changelog, $stdout)
